In [6]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

In [7]:
##붓꽃 데잍터셋 로드
iris = load_iris()

#데이터 세트에서 피처만으로 된 데이터를 넘파이로 가지고 있음.
iris_data = iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블 데이터를 넘파이로 가지고 있음.
iris_label = iris.target
print(iris_label)
print(iris.target_names)

iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
iris_df['label'] = iris_label
iris_df.head(10)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   label  
0      0  
1      0  
2      0  
3      0  
4      0  
5      0  
6      0  
7      0  
8      0  
9      0

In [8]:
##학습데이터, 테스트 데이터로 분리하기
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 1)

##첫번째 인자는 피처 데이트 세트, 두번째 인자는 레이블 데이터 세트입니다. test_size는 훈련,테스트 셋의 비율을 나타냅니다.




##객체 생성
df_clf = DecisionTreeClassifier(random_state = 11)

##fit 메소드를 이용해 학습
df_clf.fit(X_train, y_train)

##테스트 데이터에 대한 예측값 반환
pred = df_clf.predict(X_test)

##정확도 비교
print("accuracy: {0:.4f}".format(accuracy_score(y_test, pred)))

accuracy: 0.9667


In [ ]:
##과정 정리
'''
1. 데이터 세트 분리
2. 학습 데이터를 기반으로 머신러닝 알고리즘 적용하여 학습
3. 학습된 모델을 이용하여 테스트 데이터분류 예측
4. 정확도를 비교하여 모델 성능 평가
'''

In [ ]:
'''
지도학습의 두 축인 분류와 회귀의 다양한 알고리즘을 구현한 모든 사이킷런 클래스는 fit, predict만을 이용해
간단히 학습과 예측 결과를 반환합니다.
분류는 Classifier, 회귀는 Regressor로 지칭합니다.
두 클래스를 합친 클래스를 Estimator라고 합니다.
'''

In [11]:
##사이킷런 내장 데이터셋은 딕셔너리 형태로 되어있습니다.
iris_data = load_iris()
iris_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
'''
data는 피처의 데이터 세트를 가리킵니다.
target는 분류 시 레이블 값, 회귀일 때는 숫자 결과값 데이터 세트입니다.
target_names는 개별 레이블의 이름입니다.
feature_names는 피처의 이름을 나타냅니다.
DESCR은 데이터 세트에 대한 설명과 각 피처의 설명을 나타냅니다.
'''

In [ ]:
'''
모델이 학습데이터에만 과도하게 최적화되어 실제 예측을 다른 데이터로 수행할 때 예측 성능이 과도하게 떨어지는 overfitting이 발생할
수 있습니다. 이를 개선하기 위해 교차 검증을 이용합니다.
교차 검증은 학습 데이터를 다시 분할하여 학습데이터와 검증 데이터로 나눈 후, 1차적으로 평가가 끝난 뒤, 테스트 데이터로 평가를 
하는 것을 말합니다.

K 폴드 교차 검증은 가장 보편적으로 사용되는 교차 검증 기법입니다.
K개의 데이터 폴드 세트를 만들어서 K번만큼 각 폴데 세트에 학습과 검증 평가를 반복적으로 수행하는 방법입니다.
그 후 전체 결과를 평균한 결과를 가지고 예측 성능을 평가합니다.
사이킷런에서는 KFold와 StratifiedKFold클래스를 통해 K 폴드 교차 검증 프로세스를 구현합니다.
'''

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features  = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state = 156)

#5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits = 5)
cv_accuracy = []
print("데이터 세트 크기: ", features.shape[0])

데이터 세트 크기:  150


In [16]:
##KFold객체의 split함수를 호출하여 전체 데이터를 폴드 데이터 세트로 분리할 수 있습니다. 이대 split함수는 분할된 데이터의 인덱스를 
##반환합니다. 
n_iter = 0

for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(X_train, y_train)
    pred = df_clf.predict(X_test)
    n_iter += 1
    
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print("\n#{0} 검증 세트 인덱스: {1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)
print("평균 정확됴: ", np.mean(cv_accuracy))


#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30

#5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
평균 정확됴:  0.9933399999999999


In [ ]:
###Stratified K폴드
'''
Stratified K폴드는 불균형한 분포를 가진 데이터 집합을 위한 폴드 방식입니다.
이때 특정 레이블 값이 특이하게 많거나 적어서 분포가 치우치는 것을 말합니다.
이를 막기 위해 원본 데이터와 유사한 값의 분포를 학습/테스트 세트에도 유지하는 게 중요합니다.
이를 StratifiedKFold를 통해 개선해 보도록 하겠습니다.
'''

In [17]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [18]:
##이슈가 발생하는 현상 도출
kfold = KFold(n_splits = 3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print("## 교차검증: {0}".format(n_iter))
    print("학습 레이블 데이터 분포: \n", label_train.value_counts())
    print("검증 레이블 데이터 분포: \n", label_test.value_counts())

## 교차검증: 1
학습 레이블 데이터 분포: 
 2    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    50
Name: label, dtype: int64
## 교차검증: 2
학습 레이블 데이터 분포: 
 2    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    50
Name: label, dtype: int64
## 교차검증: 3
학습 레이블 데이터 분포: 
 1    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    50
Name: label, dtype: int64


In [ ]:
'''
결과를 보면 학습 레이블과 검증 레이블이 완전히 다른 값으로 추출되었습니다. 따라서 여기서는 KFold가 아닌, 
StratifiedKFold를 사용해야 합니다. 이때는 split 함수에 인자로 피처 데이터 뿐만 아니라 레이블 데이터도 들어갑니다.
'''

In [21]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits = 3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print("## 교차검증: {0}".format(n_iter))
    print("학습 레이블 데이터 분포: \n", label_train.value_counts())
    print("검증 레이블 데이터 분포: \n", label_test.value_counts())

## 교차검증: 1
학습 레이블 데이터 분포: 
 2    34
1    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    17
0    17
2    16
Name: label, dtype: int64
## 교차검증: 2
학습 레이블 데이터 분포: 
 1    34
2    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    17
0    17
1    16
Name: label, dtype: int64
## 교차검증: 3
학습 레이블 데이터 분포: 
 0    34
2    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    17
1    17
0    16
Name: label, dtype: int64


In [24]:
###위 결과를 보시면 데이터 분할이 잘 된 것을 확인할 수 있습니다. 이를 이용하여 붓꽃 데이터를 교차검증 하도록 하겠습니다.
dt_clf = DecisionTreeClassifier(random_state = 156)

skfold = StratifiedKFold(n_splits = 3)
n_iter= 0
cv_accuracy = []

for train_index, test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = df_clf.predict(X_test)
    
    n_iter += 1
    
    accuracy = np.round(accuracy_score(pred, y_test), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print("\n#{0} 검증 세트 인덱스: {1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)
print(cv_accuracy)
print("평균 정확도: ", np.mean(cv_accuracy))
    


#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 100, 검증 데이터 크기: 50

#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50

#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도: 1.0, 학습 데이터 크기: 100, 검증 데이터 크기: 50

#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
[1.0, 0.98, 1.0]
평균 정확도:  0.9933333333333333


In [25]:
##위 폴딩 알고리즘을 하나로 압축한 함수가 cross_val_score()입니다. 
##주요 파라미터로는 estimator, X,y, scoring, cv입니다.
##estimator는 회귀인지 분류인지, X는 피처 데이터, y는 레이블 데이터, cv는 교차 검증 폴드 수 입니다.
##scoring는 예측 성능 평가 지표를 기술합니다.
##함수의 반환값은 scoring에 지정된 성능 지표 측정값을 배열 형태로 반황합니다.

In [26]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.tree import DecisionTreeClassifier

iris_data = load_iris()
df_clf = DecisionTreeClassifier(random_state = 156)

data = iris_data.data
label = iris_data.target

scores = cross_val_score(df_clf, data, label, cv = 3, scoring="accuracy")
print("교차 검증별 정확도: ", np.round(scores, 4))
print("평균 검증 정확도:", np.round(np.mean(scores),4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [ ]:
'''
데이터 전처리는 머신러닝 알고리즘만큼 중요합니다.
사이킷런의 머신러닝 알고리즘을 적용하기 위해서는 데이터에 미리 처리해야 할 기본 사항이 있습니다.
첫번째로 결손값을 허용하지 않습니다. 따라서 결손값은 피처의 평균값으로 대체하거나 아얘 드롭, 또는 데이터를 잘 반영할 수 있는 값으로
대체되어야 합니다.
두번째는 문자열 값 입력을 허용하지 않습니다. 따라서 모든 문자열 데이터를 숫자로 바꿔야합니다. 

대표적인 인코딩 방식은 레이블 인코딩과 원-핫 인코딩입니다.

레이블 인코딩은 카테고리 피처를 숫자 값으로 변환하는 것입니다.
레이블 인코딩은 LabelEncoder클래스를 통해 구현합니다.
'''

In [28]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환 값: ", labels)

인코딩 변환 값:  [0 1 4 5 3 3 2 2]


In [29]:
##어떤 문자열이 어떤 숫자로 변했는지 알기 위해 클래스 속성인 classes_값을 확인하면 됩니다.
print(encoder.classes_)

['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [30]:
##inverse_transform함수를 통해 다시 디코딩할 수 있습니다.
print(encoder.inverse_transform([4,5,2,0,1,1,3,3]))
'''
레이블 인코딩의 문제점은 숫자 값의 크고 작음에 대한 특성이 작용하여 예측 성능이 떨어질 수 있습니다.
트리 계열의 알고리즘에서는 숫자의 이런 특성을 반영하지 않지만, 회귀와 같은 알고리즘에서는 적용하지 않아야 합니다.
이러한 문제점을 해결한 인코딩 방식이 원-핫 인코딩입니다.
'''

['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [ ]:
'''
원-핫 인코딩은 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지는 0을 표시하느 방법입니다.
OneHotEncoder클래스를 통해 구현할 수 있습니다.
여기서 주의할점은 모든 문자열 값이 숫자형 값으로 변환되어야 하며, 입력 값으로 2차원 데이터를 받아야합니다.
'''

In [33]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

##우선 문자열을 숫자로 바꿔야 합니다. 따라서 앞에서 다뤘던 레이블 인코딩을 먼저 해줍니다.

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

##2차원 데이터로 바꿔야합니다.
labels = labels.reshape(-1,1)
print(labels)
print('\n')
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print(oh_labels.toarray())

##판다스에서는 get_dummies를 통해 굳이 문자열을 숫자형으로 바꾸지 않고 바로 원핫인코딩 할 수 있는 함수가 있습니다.

[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [ ]:
'''
서로 다른 변수의 값 변위를 일정한 수준으로 맞추는 작업을 피처 스케일링이라고 합니다.
표준화와 정규화가 있습니다.
표준화는 평균이 0, 분산이 1인 정규 분포를 가진 값으로 변환하는 것이고,
정규화는 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념입니다.
'''

In [36]:
##StandardScaler는 표준화를 지원하는 클래스입니다. 
from sklearn.preprocessing import StandardScaler
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

print('mean: ', iris_df.mean())
print("\n")
print("var: ", iris_df.var())

mean:  sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64


var:  sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [38]:
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print(iris_df_scaled.mean())
print("\n")
print(iris_df_scaled.var())
##결과를 보시면 평균이 0 분산이 1에 가까운 값으로 변한것을 확인할 수 있습니다.

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64


sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [40]:
##MinMaxScaler클래스를 통해 데이터 값을 0~1로 변환할 수 있습니다.
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaler = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaler, columns = iris.feature_names)
print("min: ", iris_df_scaled.min())
print("\n")
print("max: ", iris_df_scaled.max())

##결과를 보시면 최소값이 0, 최대값이 1로, 0~1사이의 값으로 변한 것을 알 수 있습니다.

min:  sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64


max:  sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
